services:
    _defaults:
        autowire: true

    Sowieso\ModalBundle\Modal\Builder:
        arguments:
            - '@contao.routing.scope_matcher'
            - '@contao.image.studio'
            - '@contao.insert_tag.parser'
            - '@Sowieso\ModalBundle\Modal\ContentType'
            - '@Sowieso\ModalBundle\Modal\OpeningType'

    Sowieso\ModalBundle\Modal\Controller:
        arguments:
            - '@Sowieso\ModalBundle\Modal\Builder'

    Sowieso\ModalBundle\Modal\ContentType:
        class: Sowieso\ModalBundle\Modal\ContentType

    Sowieso\ModalBundle\Modal\OpeningType:
        class: Sowieso\ModalBundle\Modal\OpeningType
