services:
    _defaults:
        autowire: true

    Sowieso\ModalBundle\Modal\Builder:
        arguments:
            - '@contao.routing.scope_matcher'
            - '@contao.image.studio'
            - '@contao.insert_tag.parser'

    Sowieso\ModalBundle\Modal\Controller:
        arguments:
            - '@Sowieso\ModalBundle\Modal\Builder'
