services:
    _defaults:
        autowire: true

    Sowieso\ModalBundle\Modal\ModalConfig:
        arguments:
            - '@contao.insert_tag.parser'
            - '@contao.image.studio'

    Sowieso\ModalBundle\Modal\ModalElement:
        arguments:
            - '@contao.routing.scope_matcher'
            - '@Sowieso\ModalBundle\Modal\ModalConfig'
